export const mockFallback = {
  leads: [
    {
      id: 1,
      name: 'Scott Hayes',
      type: 'Buyer',
      score: 92,
      status: 'Hot',
      phone: '+1 (602) 555-0142',
      email: 'scott.hayes@email.com',
      budget: '$700K-$800K',
      neighborhood: 'Scottsdale',
      last_contact: '6 days ago',
      activity: JSON.stringify([
        'Viewed 650 Maple St 4 times today',
        'Saved 650 Maple St',
        'Opened last 2 emails within 10 minutes',
        'Returned to site after 6-day absence',
      ]),
    },
    {
      id: 2,
      name: 'Maria Gonzalez',
      type: 'Buyer',
      score: 78,
      status: 'Warm',
      phone: '+1 (480) 555-0198',
      email: 'maria.g@email.com',
      budget: '$450K-$550K',
      neighborhood: 'Phoenix',
      last_contact: '2 days ago',
      activity: JSON.stringify([
        'Viewed 3 listings',
        'Requested info on 1842 Camelback',
      ]),
    },
    {
      id: 3,
      name: 'David Kim',
      type: 'Seller',
      score: 61,
      status: 'Warm',
      phone: '+1 (602) 555-0167',
      email: 'david.kim@email.com',
      budget: null,
      neighborhood: 'Tempe',
      last_contact: '4 days ago',
      activity: JSON.stringify([
        'Requested home valuation',
        'Viewed market report',
      ]),
    },
  ],
  transactions: [
    {
      id: 1,
      name: 'Johnson — 650 Maple St',
      stage: 'Closing',
      deadline: 'Apr 21, 2026',
      hours_until_deadline: 72,
      value: 485000,
      open_issues: JSON.stringify([
        'Inspection note still open',
        'Final walkthrough not scheduled',
      ]),
      urgency: 'critical',
    },
    {
      id: 2,
      name: 'Williams — 1842 Camelback',
      stage: 'Inspection',
      deadline: 'Apr 25, 2026',
      hours_until_deadline: 168,
      value: 520000,
      open_issues: JSON.stringify(['Inspection report pending']),
      urgency: 'high',
    },
  ],
  tasks: [
    { id: 1, type: 'Call', contact: 'Scott Hayes', due: '9:00 AM', priority: 'high', completed: 0 },
    { id: 2, type: 'Call', contact: 'Maria Gonzalez', due: '10:00 AM', priority: 'high', completed: 0 },
    { id: 3, type: 'Text', contact: 'James Martinez', due: '9:30 AM', priority: 'high', completed: 0 },
    { id: 4, type: 'Text', contact: 'Johnson File', due: '10:30 AM', priority: 'high', completed: 0 },
    { id: 5, type: 'Email', contact: 'Williams File', due: '1:00 PM', priority: 'medium', completed: 0 },
    { id: 6, type: 'Other', contact: 'Update MLS listings', due: '3:00 PM', priority: 'low', completed: 0 },
  ],
  listings: [
    { id: 1, address: '650 Maple St, Scottsdale', price: 749000, beds: 4, baths: 3, status: 'Active', days_on_market: 12, views: 47 },
    { id: 2, address: '1842 Camelback Rd, Phoenix', price: 520000, beds: 3, baths: 2, status: 'Showing', days_on_market: 8, views: 31 },
  ],
  smartPlans: [
    {
      id: 1,
      name: 'Lofty Bloom Companion',
      status: 'Paused',
      issue: 'Email bounce on 3 leads',
      affected_leads: JSON.stringify(['Amy Chen', 'David Kim', 'Maria Gonzalez']),
      last_run: 'Yesterday',
    },
  ],
  appointments: [
    { id: 1, time: '2:00 PM', address: '1842 Camelback Rd, Phoenix', contact: 'James Martinez', type: 'Showing' },
    { id: 2, time: '4:30 PM', address: '650 Maple St, Scottsdale', contact: 'Roberts Family', type: 'Showing' },
  ],
}
